language: cpp
before_install:
 - cmake --version
install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libgl1-mesa-dev
script:
 - mkdir build-src && cd build-src
 - cmake ../src
 - make
 - ./platform_test

notifications:
  irc:
    channels:
      - "chat.freenode.net#twineshaft"
    on_success: change
    on_failure: always
